# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAlrlri1iqoRozV6bRGZ6o_90VG4XEG4
"""

from google.colab import files

# This pops up a file picker — select BOTH files when prompted:
# - dailyActivity_merged.csv
# - minuteSleep_merged_csv.zip
uploaded = files.upload()

from google.colab import files

# This pops up a file picker — select BOTH files when prompted:
# - dailyActivity_merged.csv
# - minuteSleep_merged_csv.zip
uploaded = files.upload()

import zipfile
with zipfile.ZipFile('minuteSleep_merged.csv.zip', 'r') as z:
    z.extractall('.')

# Verify both CSVs are now in the working dir
!ls *.csv

from google.colab import drive
drive.mount('/content/drive')
# Then put your files in a Drive folder and read from there

"""
Wearable Activity & Sleep Cohort Analysis
Hypothesis: High-activity users have higher sleep efficiency than low-activity users.
"""
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

# ---------- 1. Load ----------
activity = pd.read_csv('dailyActivity_merged.csv')
sleep = pd.read_csv('minuteSleep_merged.csv')

print(f"Activity rows: {len(activity):,}  | unique users: {activity['Id'].nunique()}")
print(f"Sleep rows:    {len(sleep):,}  | unique users: {sleep['Id'].nunique()}")

# ---------- 2. Compute sleep efficiency per session ----------
# value: 1=asleep, 2=restless, 3=awake
# sleep_efficiency = minutes_asleep / total_minutes_in_bed
session = (sleep.groupby(['Id', 'logId'])
           .agg(in_bed=('value', 'count'),
                asleep=('value', lambda v: (v == 1).sum()))
           .reset_index())
session['efficiency'] = session['asleep'] / session['in_bed']

# Filter very short sessions (likely nap fragments / noise) — keep sessions >= 60 min
session = session[session['in_bed'] >= 60]
print(f"\nSleep sessions (>= 60 min): {len(session):,}")
print(session['efficiency'].describe())

# ---------- 3. Per-user aggregates ----------
user_eff = session.groupby('Id')['efficiency'].mean().rename('avg_efficiency')
user_steps = activity.groupby('Id')['TotalSteps'].mean().rename('avg_steps')

user_df = pd.concat([user_steps, user_eff], axis=1).dropna()
print(f"\nUsers with BOTH activity + sleep data: {len(user_df)}")
print(user_df.describe())

# ---------- 4. Cohort assignment — both splits ----------
median_steps = user_df['avg_steps'].median()
high_med = user_df[user_df['avg_steps'] >= median_steps]['avg_efficiency']
low_med  = user_df[user_df['avg_steps'] <  median_steps]['avg_efficiency']

high_cdc = user_df[user_df['avg_steps'] >= 10000]['avg_efficiency']
low_cdc  = user_df[user_df['avg_steps'] <  7000]['avg_efficiency']

print(f"\nMedian split — high (>= {median_steps:.0f} steps): n={len(high_med)}, low: n={len(low_med)}")
print(f"CDC split    — high (>=10K steps): n={len(high_cdc)}, low (<7K): n={len(low_cdc)}")

# ---------- 5. Assumption checks ----------
print("\n--- Assumption checks (median split) ---")
print(f"Shapiro high cohort: stat={stats.shapiro(high_med).statistic:.3f}, p={stats.shapiro(high_med).pvalue:.4f}")
print(f"Shapiro low cohort:  stat={stats.shapiro(low_med).statistic:.3f}, p={stats.shapiro(low_med).pvalue:.4f}")
print(f"Levene equal var:    stat={stats.levene(high_med, low_med).statistic:.3f}, p={stats.levene(high_med, low_med).pvalue:.4f}")

# ---------- 6. Tests ----------
def cohens_d(a, b):
    pooled = np.sqrt((a.var(ddof=1) + b.var(ddof=1)) / 2)
    return (a.mean() - b.mean()) / pooled

print("\n--- Welch's t-test (median split) ---")
t, p = stats.ttest_ind(high_med, low_med, equal_var=False)
d = cohens_d(high_med, low_med)
print(f"high mean={high_med.mean():.4f}, low mean={low_med.mean():.4f}")
print(f"t={t:.3f}, p={p:.4f}, Cohen's d={d:.3f}")

print("\n--- Mann-Whitney U (median split, non-parametric backup) ---")
u, p_u = stats.mannwhitneyu(high_med, low_med, alternative='two-sided')
print(f"U={u:.1f}, p={p_u:.4f}")

print("\n--- Welch's t-test (CDC split, sensitivity check) ---")
if len(high_cdc) >= 3 and len(low_cdc) >= 3:
    t_c, p_c = stats.ttest_ind(high_cdc, low_cdc, equal_var=False)
    d_c = cohens_d(high_cdc, low_cdc)
    print(f"high mean={high_cdc.mean():.4f}, low mean={low_cdc.mean():.4f}")
    print(f"t={t_c:.3f}, p={p_c:.4f}, Cohen's d={d_c:.3f}")
else:
    print(f"Skipped — cohort too small (n_high={len(high_cdc)}, n_low={len(low_cdc)})")

# ---------- 7. Visualizations ----------
sns.set_style("whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Scatter — steps vs efficiency per user
axes[0].scatter(user_df['avg_steps'], user_df['avg_efficiency'], s=80, alpha=0.7, color='#2E86AB')
axes[0].axvline(median_steps, color='gray', linestyle='--', alpha=0.5, label=f'Median = {median_steps:.0f}')
axes[0].set_xlabel('Avg Daily Steps (per user)')
axes[0].set_ylabel('Avg Sleep Efficiency')
axes[0].set_title('Per-User: Activity vs Sleep Efficiency')
axes[0].legend()

# Plot 2: Boxplot — cohort comparison
cohort_df = pd.DataFrame({
    'Sleep Efficiency': pd.concat([high_med, low_med]).values,
    'Cohort': ['High activity'] * len(high_med) + ['Low activity'] * len(low_med)
})
sns.boxplot(data=cohort_df, x='Cohort', y='Sleep Efficiency', hue='Cohort',
            ax=axes[1], palette=['#2E86AB', '#E63946'], legend=False)
sns.stripplot(data=cohort_df, x='Cohort', y='Sleep Efficiency', ax=axes[1],
              color='black', size=5, alpha=0.6)
axes[1].set_title(f"Sleep Efficiency by Activity Cohort\n(Welch's t: p = {p:.3f}, Cohen's d = {d:.2f})")

plt.tight_layout()
plt.savefig('cohort_analysis.png', dpi=120, bbox_inches='tight')
plt.close()
print("\nPlot saved: cohort_analysis.png")

from google.colab import files
files.download('cohort_analysis.png')